# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-05 04:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=100)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_posted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[(b'This story is a spam or a scam', b'This story is a spam or a scam'), (b'This story puts people at risk', b'This story puts people at risk'), (b"This story shouldn't be here ", b"This story shouldn't be here")], default=b'none', max_length=30)),
                ('reported_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reported_story', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scribble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('points', models.IntegerField(default=0)),
                ('hash_tags', models.ManyToManyField(related_name='hashtags_story', to='Story.HashTag')),
                ('likers', models.ManyToManyField(related_name='scribbles_liked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_uploaded', to=settings.AUTH_USER_MODEL)),
                ('user_tags', models.ManyToManyField(related_name='usertags_story', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='scribble',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Story.Scribble'),
        ),
        migrations.AddField(
            model_name='comment',
            name='scribble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Story.Scribble'),
        ),
    ]
