# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribble',
            name='headline',
            field=models.CharField(default=b'no title', max_length=20),
        ),
    ]
