# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0002_scribble_headline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scribble',
            old_name='text',
            new_name='story',
        ),
    ]
