# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0003_auto_20160606_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scribble',
            name='date',
        ),
        migrations.RemoveField(
            model_name='scribble',
            name='time',
        ),
        migrations.AddField(
            model_name='scribble',
            name='on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 10, 10, 29, 52, 889867, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
