# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 04:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Story', '0004_auto_20160610_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribble',
            name='reporters',
            field=models.ManyToManyField(related_name='stories_reported', to=settings.AUTH_USER_MODEL),
        ),
    ]
