# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 04:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0005_scribble_reporters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scribble',
            name='likers',
            field=models.ManyToManyField(null=True, related_name='scribbles_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
