# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 04:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0007_auto_20160611_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scribble',
            name='hash_tags',
            field=models.ManyToManyField(blank=True, related_name='hashtags_story', to='Story.HashTag'),
        ),
        migrations.AlterField(
            model_name='scribble',
            name='reporters',
            field=models.ManyToManyField(blank=True, related_name='stories_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scribble',
            name='user_tags',
            field=models.ManyToManyField(blank=True, related_name='usertags_story', to=settings.AUTH_USER_MODEL),
        ),
    ]
