# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-12 01:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0008_auto_20160611_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_story', to=settings.AUTH_USER_MODEL),
        ),
    ]
