# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-14 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0011_auto_20160613_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scribble',
            name='is_poem',
        ),
        migrations.RemoveField(
            model_name='scribble',
            name='is_quote',
        ),
        migrations.RemoveField(
            model_name='scribble',
            name='is_shtory',
        ),
        migrations.AddField(
            model_name='scribble',
            name='scribble_type',
            field=models.IntegerField(choices=[(0, b'shtory'), (1, b'poem'), (2, b'quote')], default=0),
        ),
    ]
