# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 06:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Story', '0012_auto_20160614_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribble',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='scribbles_bookmarked', to=settings.AUTH_USER_MODEL),
        ),
    ]
