# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 02:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myuser', '0003_auto_20160610_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(related_name='related_to', through='Myuser.Relationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
