# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 03:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myuser', '0006_auto_20160612_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2016, 6, 13)),
        ),
    ]
